export const HOSPITALITY_AND_EVENTS_SKILLS_TAXONOMY = `
HOSPITALITY AND EVENTS SKILLS TAXONOMY & Semantic Matching Layer
This section presents a comprehensive hospitality and events industry skills taxonomy focused on front-of-house (customer-facing) and serving roles. It includes up to 60 key roles across restaurants, bars, hotels, and event venues (using British English terms suited to London). For each role, we list common synonyms or alternate titles (to aid semantic matching) and a brief description of responsibilities. Where applicable, we also note certifications/licensing requirements (tags) that are often needed in the UK (e.g. food hygiene training, alcohol licence, security licence). This taxonomy will help the Gigfolio Coach and future Able agents map user-mentioned skills to standardized role names in real time via semantic and vector similarity matching.
Food & Beverage Service Roles (Restaurants, Pubs & Bars)
●	Waitstaff (Waiter/Waitress, Server) : Front-line serving staff who take food and drink orders, serve meals, and ensure guests have an enjoyable dining experience . They are the face of a restaurant and liaise between customers and the kitchen. Certifications: Basic food hygiene training (Level 1) is expected for anyone handling food (formal certificate not legally required but training is required ).

●	Bartender (Bar Staff; Barman/Barmaid) : Prepares and serves alcoholic and non-alcoholic beverages at the bar. Bartenders also chat with patrons and maintain the bar’s stock and cleanliness . They must know a range of drinks and practice responsible alcohol service (e.g. checking IDs and watching for intoxication ). Certifications: In the UK, venues selling alcohol must have a Personal Licence holder supervising sales . While not every bartender is licensed, many senior bartenders or bar managers obtain the Level 2 Award for Personal Licence Holders (APLH), as each premises needs at least one personal licence holder .

●	Barback (Bar Runner, Bar Assistant) : Assists bartenders by restocking bottles, fetching supplies, cleaning glasses, and keeping the bar area stocked and clean during service. Barbacks (sometimes called bar runners or glass collectors) ensure bartenders can focus on serving customers. This is typically an entry-level support role in pubs and bars.

●	Host/Hostess (Restaurant Host, Greeter) : The host or hostess manages the front door of a restaurant, greeting arriving guests and handling reservations and waitlists . They seat guests at tables, distribute menus, and set the first impression of hospitality. This role requires excellent customer service and organization to coordinate seating and wait times . Certifications: No formal license required; strong communication skills and possibly reservation system training are needed.

●	Maître d’hôtel (Head Waiter, Dining Room Manager) : A maître d’ is the head of dining room service, overseeing waitstaff and the guest experience in an upscale restaurant. They welcome VIP guests, manage table assignments, handle customer complaints, and ensure service standards. Essentially, this is a floor manager for the restaurant dining area (common in fine dining). Certifications: No specific license; extensive hospitality experience is expected.

●	Sommelier (Wine Steward) : A wine specialist who manages the wine list and assists guests in selecting wines. A sommelier works in fine dining, suggesting wine pairings and often handling wine service (pouring, decanting). Many sommeliers pursue professional certifications in wine knowledge and service, such as the Court of Master Sommeliers or WSET (Wine & Spirit Education Trust) qualifications . These credentials attest to their expertise in viticulture, tasting, and wine service.

●	Barista (Coffee Barista) : A specialist in making coffee and espresso-based drinks. Baristas typically work in cafés or coffee bars, operating espresso machines, frothing milk, and serving teas and other hot beverages. They often handle cash and food items like pastries. Certifications: No formal requirement, though many baristas undergo barista training courses. Level 1 food safety training is recommended if handling milk and food.

●	Busser / Food Runner (Commis Waiter, Runner) : Support staff who clear tables and deliver food to tables quickly. Bussers focus on clearing used dishes and resetting tables, while food runners primarily run plates from the kitchen to guests . These roles help maintain a clean dining area and assist waiters by keeping water glasses filled and bringing dishes out promptly . Certifications: Basic hygiene training and on-the-job training are typical. These are entry-level positions in front-of-house teams.

●	Banquet Server (Catering Waitstaff) : A server who works at events, banquets, or catering functions rather than a regular restaurant shift. Banquet servers set up function rooms, serve plated meals or staff buffets, and clear tables during events like weddings or conferences. They need to carry large trays and often serve many guests at once. Certifications: Food hygiene training (Level 2 for catering) is common, and alcohol service training if serving drinks.

●	Banquet Captain (Event Captain, Lead Server) : A team leader for banquet servers. The banquet captain coordinates the service during an event, directing the waitstaff, timing the courses, and ensuring the event service runs smoothly. They communicate with the kitchen and event organizers to execute the banquet schedule. Certifications: Usually needs strong experience; may hold a Personal Licence if alcohol is served, and often has advanced food safety training since they supervise catering operations.

●	Restaurant Manager (Front-of-House Manager) : Oversees daily operations of a restaurant’s front-of-house, including supervising staff, handling customer issues, and managing service quality . They coordinate with the kitchen, manage schedules, and ensure guests have a positive experience. In smaller venues this role might be combined with general manager. Certifications: No mandatory license, but often a Level 3 Food Hygiene certificate (for managers) is recommended . If the restaurant serves alcohol, the manager is typically a Personal Licence holder authorized to supervise alcohol sales .

●	Bar Manager / Pub Manager : Runs the operations of a bar or pub, including managing bar staff and inventory, ordering stock, and maintaining licensing compliance. A pub/bar manager creates work rotas, ensures responsible alcohol service, and often also serves customers during busy times. Certifications: Personal Licence (APLH) is typically required for the designated premises supervisor of a pub . Bar managers also benefit from Level 2 or 3 food safety training if the venue serves food.

●	Catering Manager (Event Catering Manager) : Manages catering services for events or venues. A catering manager plans menus with chefs, organizes catering staff, and ensures food preparation and service meet client expectations. For example, they might coordinate catering for a conference, arranging both the kitchen production and the front-of-house service at the event. Certifications: Food Hygiene Level 3 (management) is often expected, and if catering includes alcohol, a Personal Licence might be needed.

●	Mixologist (Cocktail Specialist) : (Often encompassed under Bartender). A mixologist is an expert in crafting cocktails and specialized drinks. This term highlights creative drink-making skills : mixologists design signature cocktails, understand flavor profiles, and may enter cocktail competitions. In many establishments, the head bartender or a cocktail bartender serves this role. Certifications: Same as bartender (no separate license; possibly attended mixology courses).

Hotel & Guest Services Roles (Accommodation Sector)
●	Hotel Receptionist (Front Desk Agent) : The first point of contact for hotel guests at the front desk. Receptionists check guests in and out, manage reservations, answer inquiries, and provide keys. They handle payments and often serve as an information hub for guests about hotel amenities. Excellent customer service and problem-solving are required, as they address guest requests or complaints promptly. Certifications: No formal license; typically trained in the hotel’s property management system. (In luxury settings, may have completed hospitality NVQs or apprenticeships.)

●	Concierge : A concierge acts as a personal assistant to hotel guests, arranging anything from restaurant reservations and theatre tickets to transportation and local tours . They have deep knowledge of local attractions and services, and they handle special requests to enhance the guest experience (for example, booking a spa service or finding a last-minute florist) . Certifications: No legal requirements, but concierges often undergo professional training; some are members of Les Clefs d’Or (the Golden Keys concierge society) which is a mark of excellence . Key skills include communication, local expertise, and resourcefulness.

●	Porter (Bellhop, Luggage Porter) : A hotel porter assists guests with their luggage and escorts them to their rooms. In high-end hotels, they may also run errands, deliver room service items, or handle guest requests for minor tasks. A bellhop (common American term) or luggage porter typically works closely with the concierge and front desk. Certifications: No formal requirements; needs good customer service and physical stamina. (In some settings called hall porter or door porter if stationed at the entrance).

●	Doorman (Hotel Doorman, Commissionaire) : A doorman stands at the hotel entrance to welcome guests, open doors, hail taxis, and provide security by monitoring who enters. In London, upscale hotels often have uniformed doormen (sometimes called commissionaires). This role combines courtesy with a security element, ensuring only patrons and guests enter the premises. Certifications: No special license (unlike a nightclub doorman, see Door Supervisor below), but training in customer service and sometimes basic security awareness is needed.

●	Night Auditor (Night Receptionist) : The night auditor works overnight at the hotel front desk, handling late check-ins/outs and running the daily financial reports. This role is a mix of front desk duties and accounting: at night, the auditor posts room charges, reconciles the day’s transactions, and prepares reports for management. They often also act as the duty manager during nighttime, handling any guest issues that arise during the night shift. Certifications: No specific license; skills in accounting and use of hotel management software are required.

●	Guest Relations Manager (Guest Services Executive) : Focuses on VIP guests and overall guest satisfaction in a hotel. The guest relations manager addresses any special requests, resolves issues for dissatisfied guests, and often manages loyalty program guests or important clients to ensure they have a seamless stay. They may train staff in service excellence and handle guest feedback and reviews. Certifications: No mandated certifications; background in hospitality management and customer care training is common.

●	Front Office Manager (Front Desk Manager) : Manages the entire front office team (receptionists, night auditors, porters, concierge). They ensure smooth check-in/check-out processes, staff scheduling, and that guest service policies are followed . The front office manager often reports to the hotel general manager and handles hiring/training of front desk staff. Certifications: Typically has a hospitality management qualification. No specific license required.

●	Duty Manager (Shift Manager) : The manager on duty overseeing hotel operations during a given shift (often evenings or weekends when the general manager is off). Duty managers handle any operational issues across departments, from front desk to housekeeping or food service, to keep the property running smoothly for guests. They are empowered to make decisions and resolve emergencies or guest complaints in the absence of higher management. Certifications: Experience-based role; usually no special license.

●	Hotel Manager (General Manager) : The executive in charge of all aspects of a hotel’s operation. The hotel general manager (GM) sets service standards, manages department heads (front office, housekeeping, F&B, etc.), and is responsible for financial performance. While this role goes beyond front-of-house, it’s included for hierarchy completeness. The GM ensures guest satisfaction and efficient operations at the highest level. Certifications: No single license, but a degree in hospitality management is common. If the hotel has licensed bars/restaurants, the GM usually also holds a Personal Licence for alcohol by default as a best practice.

●	Valet Parking Attendant (Car Jockey) : Provides parking services at hotels, restaurants, or events. A valet greets guests arriving by car, parks the vehicle for them, and retrieves it on departure. This role requires safe driving skills and courteous interaction. It is common at luxury hotels or private clubs in London. Certifications: A valid driving licence is required. Training in customer service and high-end vehicle handling is typically provided.

●	Butler (Personal Butler) : A butler provides highly personalized service to guests, particularly in luxury hotels or estate settings. Duties can include unpacking luggage, ironing clothes, arranging in-room dining, and generally being on call for a guest’s needs. Some high-end London hotels offer butler service for suites. Certifications: No legal requirement; often trained in bespoke service (etiquette, wine service, etc.). In some cases, butlers have attended specialized butler training schools.

Event & Venue Roles (Events, Catering & Entertainment Venues)
●	Event Coordinator (Event Planner, Event Organiser) : Plans and coordinates events such as conferences, corporate functions, or parties. An event coordinator liaises with clients to understand their needs, books venues and services, and ensures all details (catering, AV, scheduling) are arranged. They handle logistics leading up to the event and often assist the event manager on the day. Certifications: Not mandatory, but many have an events management diploma or certification. Key skills include organization and vendor management.

●	Event Manager (Events Planner/Director) : Oversees the overall execution of events : from initial concept through planning to on-site management. Event managers negotiate with venues and suppliers, manage budgets and timelines, and supervise event staff. They ensure compliance with health, safety, and insurance regulations during events . On event day, they troubleshoot issues and make sure everything runs smoothly . Certifications: No license required, but a degree or certificate in Events Management or Hospitality is common. Large events may require knowledge of risk assessments and sometimes first aid or safety certifications (e.g., some event managers obtain a First Aid at Work certificate, especially given that since 2025 in the UK security staff must have first aid training ).

●	Wedding Planner (Bridal Consultant) : A specialist event planner who coordinates weddings. Wedding planners work with couples to design the wedding theme, book venues, caterers, florists, photographers, and manage the event schedule (ceremony, reception). They ensure the wedding day activities go as planned and handle any issues (like weather plan B, vendor no-shows) without burdening the couple. Certifications: No formal requirement; many are independent experts often with an events planning background. Communication and creativity are key skills.

●	Venue Manager (Venue Operations Manager) : Manages the operations of an event venue or theatre. The venue manager handles scheduling of events, coordinates venue staff (ushers, box office, technicians), and ensures the facility is ready and compliant for each event. They often oversee front-of-house and back-of-house teams to deliver events successfully. Certifications: No specific license; experience in events/hospitality management needed. If the venue serves alcohol (e.g. a concert hall bar), the venue manager might hold a Personal Licence.

●	Front of House Manager (Theatre/Events FOH Manager) : In theatres or large venues, this manager is responsible for the front-of-house staff and audience experience. They supervise ushers, ticket takers, and concession staff, making sure patrons are seated correctly, safety protocols are followed, and the show/event starts on time. They handle any patron issues in the lobby or seating areas. Certifications: No mandated certification; typically trained in customer service and crowd management basics. Familiarity with emergency evacuation procedures is important.

●	Usher (Event Usher, Theatre Usher) : Ushers guide attendees to their seats at events or performances, check tickets, and provide programs. They also enforce venue rules (e.g. no photography if not allowed, or keeping exits clear) and assist in crowd control in their section. Ushers are a primary customer service touchpoint in theatres, concert halls, and sports venues. Certifications: No special license; on-the-job training. For large events, they may receive safety training (e.g. fire safety, basic first aid).

●	Box Office Attendant (Ticket Seller, Ticketing Agent) : Sells and distributes tickets at an event venue’s box office (ticket counter). They handle customer inquiries about events, process ticket purchases (cash or electronic), and manage will-call or ticket collection. In modern venues, this role may also involve using digital ticketing systems. Certifications: No formal requirements; requires cash handling skills and customer service.

●	Coat Check Attendant (Cloakroom Attendant) : Manages the cloakroom at venues or events, taking guests’ coats, bags, or umbrellas and giving claim tickets. At the end of the event, they return items to the correct owners. This role requires an organized system and honesty/trustworthiness. Certifications: None required; needs good organizational skills. (Common in venues like nightclubs, theatres especially during winter months.)

●	Master of Ceremonies (MC, Event Host) : An MC or host is the official presenter at an event, responsible for guiding the program. For example, at a conference they introduce speakers, or at a wedding they announce the couple and direct guests’ attention to key moments. In corporate events, an MC keeps the agenda flowing on time. Certifications: No formal certification; public speaking ability is crucial. Often the MC is a hired talent or a staff member comfortable in front of crowds.

●	Event Steward (Crowd Steward, Event Marshal) : Stewards are deployed at large events (festivals, sports matches, concerts) to help with crowd management and safety. They check tickets at entrances, give directions, monitor crowds for any disturbances, and guide people during emergency evacuations. Stewards are typically not full security guards but act as the eyes and ears to alert security if needed. Certifications: Stewards must undergo basic safety training; many are required by employers to have or obtain the Level 2 Award in Understanding Stewarding at Spectator Events, and larger events require some stewards to hold first aid training. (Security tasks like searching or ejecting people are handled by SIA-licensed staff, see Door Supervisor below.)

●	Banqueting Manager (Events Catering Manager) : Oversees banquet operations for events, often in a hotel or conference center. The banqueting manager coordinates with clients on banquet setup, manages the banquet staff (servers, bartenders), plans table layouts, and ensures the food service is executed correctly for large functions . They also handle post-event breakdown and feedback. Certifications: Food Safety Level 3 is typically expected; no license, but if responsible for alcohol service, they should be a Personal Licence holder as well.

●	Convention Services Manager : (Seen in large hotels or convention centers) Works with conference or convention organizers to arrange meeting spaces, AV equipment, catering, and accommodations. They act as the liaison between the event planners (clients) and the venue’s departments. This is a planning-heavy role ensuring that conferences and large meetings at the venue meet the client’s needs. Certifications: Experience in event management; no specific license.

Nightlife & Security-Related Front-of-House Roles
●	Door Supervisor (Bouncer, Door Staff) : A licensed security professional who controls entry at pubs, clubs, and event venues. Door supervisors (often colloquially bouncers or doormen in clubs) check IDs and tickets, manage queues, enforce dress codes, and refuse entry to intoxicated or troublesome individuals . They ensure the safety of patrons and staff by handling any disturbances or removing individuals if necessary . Certifications: Security Industry Authority (SIA) Door Supervisor Licence is legally required in the UK to work in this role . To get the SIA licence, one must complete approved training (including Emergency First Aid at Work since 2021) and pass background checks .

●	Security Guard (Event Security Guard) : (Distinct from door supervisors who specifically guard licensed premises.) Security guards at events or hotels might patrol the venue, monitor CCTV or access points, and respond to incidents. Some large hotels employ in-house security guards to handle emergencies and lost property, etc. Certifications: SIA Security Guard Licence if not performing door supervisor activities (though many opt for the Door Supervisor licence which also covers security guarding). They need to be SIA-licensed to legally work in security roles in the UK .

●	VIP Host (VIP Guest Host) : Common in nightclubs or high-end lounges, a VIP host attends to important guests or table-service clients. They manage reservations for VIP tables, greet high-paying patrons, and ensure these guests receive prompt service (bottle service, etc.). Essentially, they are customer service liaisons for VIP clientele, sometimes also handling celebrity guests. Certifications: No formal requirements; strong interpersonal and hospitality skills needed.

●	Casino Croupier (Casino Dealer) : A croupier deals cards or operates games (roulette, blackjack, etc.) at a casino. This is a customer-facing role in the gaming hospitality sector, requiring quick math skills and the ability to explain game rules to players. They also enforce game rules and maintain a lively, friendly atmosphere at the table. Certifications: No external license (casinos train their dealers). However, casino employees must be licensed by the Gambling Commission in the UK (casino operational license), which includes background checks. Croupiers typically undergo specialized training courses in dealing techniques.

●	Casino Host : A customer relations role in casinos, similar to a VIP host but for gamblers. Casino hosts ensure regular and high-value players (high rollers) are looked after : offering complimentary services (comps), arranging hotel stays, and inviting them to events. They build relationships to encourage customer loyalty. Certifications: No formal certification; expertise in customer service and often some background in gaming or hospitality.

●	Nightclub Promoter : (Edge of FOH roles) A promoter isn’t a venue staff per se, but they work to bring guests to a nightclub or event. Promoters often stand at venue entrances or operate in social networks to invite people, manage guest lists, and ensure a crowd for events. While not a staff role inside the venue, they are part of the hospitality ecosystem. Certifications: None; this is usually a freelance/commission role based on marketing skills.

Each of these roles is defined with the goal of capturing different terms a user might use (for example, someone might say “I worked as a waitress” which the system should map to waitstaff, or “bouncer” which maps to door supervisor). The semantic matching layer will leverage these synonyms and descriptions, as well as vector embeddings of the role names, to intelligently match user input to the closest standardized role. For instance, if a user mentions experience as a “wine waiter at an upscale restaurant”, the system can match that to Sommelier due to the wine service context. Similarly, “front desk at a hotel” would be recognized as Hotel Receptionist or Front Desk Agent. The taxonomy ensures full coverage of the hospitality and events domain (focused on front-of-house) so that Gigfolio can accurately categorize a wide range of gig workers’ skills and job titles in this industry.
Sources:
●	Epos Now, “Front of House Positions: Roles and Responsibilities in Hospitality” : standard restaurant front-of-house roles and duties .

●	Lightspeed HQ, “What Licence Do I Need to Open a Restaurant or Bar in the UK?” : UK alcohol licensing requirements (personal licence for bar managers) .

●	National Careers Service : job profiles for Door Supervisor (security licence requirements) and Events Manager (overview of event management duties) .

●	Food Standards Agency : guidance that food handlers must be trained in hygiene (level 1/2 training for waitstaff) .

●	Wine & Spirit Education Trust (WSET) : explanation of sommelier as a trained wine waiter and certification paths (WSET, Court of Master Sommeliers) .

●	HotelContractBeds blog : describes the concierge role in hotels (personalized guest services and local expertise) .

`;
