## Health
GET {{baseUrlGig}}/health

### Register gig work
POST {{baseUrlGig}}/gig/gig-work
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "additionalInstructions": "Please bring your own tools.",
  "address": "123 Main St, Anytown, USA",
  "description": "Looking for a skilled Bartender.",
  "endDate": "2025-07-23",
  "latitude": 51.5,
  "longitude": 0.0,
  "paymentPerHour": 25,
  "skills": ["Bartender"],
  "startDate": "2025-07-20",
  "title": "Bartender"
}

### Get Gig Works
GET {{baseUrlGig}}/gig/gig-work?appRole=WORKER&sort=asc:createdAt&offset=0&limit=10&status=PENDING
Authorization: Bearer {{accessToken}}

### Get One Gig Work
GET {{baseUrlGig}}/gig/gig-work/1
Authorization: Bearer {{accessToken}}

### Get All Gig Work Payments
GET {{baseUrlGig}}/gig/gig-work/payments?offset=0&limit=10
Authorization: Bearer {{accessToken}}

### Register Gig Work Team
POST {{baseUrlGig}}/gig/work-team
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "endDateOffer": "2025-08-01",
  "gigWorkId": 1,
  "workerSkillId": 1
}

### Get Gig Work Teams
GET {{baseUrlGig}}/gig/work-team?sort=asc:createdAt&offset=0&limit=10
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "appRole": "BUYER",
  "where": {
    "fields":[
      {
        "field": "status",
        "value": "PAID"
      }
    ]
  }
}

### Get One Gig Work Team
GET {{baseUrlGig}}/gig/work-team/1/BUYER
Authorization: Bearer {{accessToken}}

### Accept Gig Work Team
PATCH {{baseUrlGig}}/gig/work-team/accept
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "accepted": true,
  "appRole": "WORKER",
  "id": 1
}

### Update Gig Work Team Payment
PATCH {{baseUrlGig}}/gig/work-team/payment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "expenses": 100,
  "id": 1,
  "received": 500,
  "taxes": 50,
  "tips": 20
}
