## Health
GET {{baseUrlGig}}/health

### Register gig work
POST {{baseUrlGig}}/gig/gig-work
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "additionalInstructions": "Please bring your own tools.",
  "address": "123 Main St, Anytown, USA",
  "description": "Looking for a skilled Bartender.",
  "endDate": "2025-07-23",
  "latitude": 51.5,
  "longitude": 0.0,
  "paymentPerHour": 25,
  "skills": ["Bartender"],
  "startDate": "2025-07-20",
  "title": "Bartender"
}

### Get Gig Works
GET {{baseUrlGig}}/gig/gig-work?appRole=WORKER&sort=asc:createdAt&offset=0&limit=10&status=PENDING
Authorization: Bearer {{accessToken}}

### Get One Gig Work
GET {{baseUrlGig}}/gig/gig-work/1
Authorization: Bearer {{accessToken}}

### Register Gig Work Team
POST {{baseUrlGig}}/gig/work-team
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "endDateOffer": "2025-08-01",
  "gigWorkId": 1,
  "workerSkillId": 1
}

### Get All Completed Gig Work Resumes
GET {{baseUrlGig}}/gig/gig-work/completed/resume?offset=0&limit=10
Authorization: Bearer {{accessToken}}
