### Register worker

POST {{baseUrlGig}}/worker/register
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "socialNetworkUrl": "https://www.example.com/profile",
    "tags": "JavaScript, Node.js"
}
