export enum CANCELLATION_PARTY {
  BUYER = 'BUYER',
  WORKER = 'WORKER',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum GIG_STATUS {
  PENDING_WORKER_ACCEPTANCE = 'PENDING_WORKER_ACCEPTANCE',
  ACCEPTED = 'ACCEPTED',
  DECLINED_BY_WORKER = 'DECLINED_BY_WORKER',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_COMPLETION_WORKER = 'PENDING_COMPLETION_WORKER',
  PENDING_COMPLETION_BUYER = 'PENDING_COMPLETION_BUYER',
  COMPLETED = 'COMPLETED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAID = 'PAID',
  CANCELLED_BY_BUYER = 'CANCELLED_BY_BUYER',
  CANCELLED_BY_WORKER = 'CANCELLED_BY_WORKER',
  CANCELLED_BY_ADMIN = 'CANCELLED_BY_ADMIN',
  DISPUTED = 'DISPUTED',
}
