export enum REGISTER_STATUS_CODE {
  ALREADY_EXIST = 'ALREADY_EXIST',
  PRIVATE_DATA_USER_CREATION_FAILED = 'PRIVATE_DATA_USER_CREATION_FAILED',
  USER_CREATION_FAILED = 'USER_CREATION_FAILED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
}

export type RegisterStatusKeys = keyof typeof REGISTER_STATUS_CODE;
