export enum REVIEW_TYPE {
  INTERNAL_PLATFORM = 'INTERNAL_PLATFORM',
  EXTERNAL_REQUESTED = 'EXTERNAL_REQUESTED',
}

export enum BADGE_TYPE {
  SKILL = 'SKILL',
  VALUE = 'VALUE',
  PLATFORM_ACHIEVEMENT = 'PLATFORM_ACHIEVEMENT',
}
