@baseUrl = http://localhost:3002/api/auth/v1

### ROOT Auth API

### GET greeting
GET {{baseUrl}}/

############################################################################

### PRIVATE GIG/ private-data-user

### GET all
GET {{baseUrl}}/private-gig/users?sort=desc:email

### GET by id
GET {{baseUrl}}/private-gig/users/1

### CREATE
POST {{baseUrl}}/private-gig/users
Content-Type: application/json

{
  "fullName": "Nuevo Usuario III",
  "email": "nuevoIII@ejemplo.com"
}

### UPDATE by id
PUT {{baseUrl}}/private-gig/users/1
Content-Type: application/json

{
  "fullName": "Usuario Actualizado II",
  "email": "actualizado@ejemplo.com"
}

### DELETE by id
DELETE {{baseUrl}}/private-gig/users/1

############################################################################

### GIG/ users

### GET all
GET {{baseUrl}}/gig/users

### GET by id
GET {{baseUrl}}/gig/users/1

### CREATE
POST {{baseUrl}}/gig/users
Content-Type: application/json

{
  "password": "your_awesome_password",
  "private_data_user_id": 1,
  "enabled": true,
  "role_id": "gig"
}

### UPDATE by id
PUT {{baseUrl}}/gig/users/1
Content-Type: application/json

{
  {
  "password": "your_awesome_password",
  "private_data_user_id": 1,
  "enabled": true,
  "role_id": "gig"
}
}

### DELETE by id
DELETE {{baseUrl}}/gig/users/1

