### ROOT Auth API

### GET health
GET {{baseUrlAuth}}/health

#############################################
################### AUTH ####################
#############################################

### POST Register
POST {{baseUrlAuth}}/register
Content-Type: application/json

{
  "fullName": "<your_full_name>",
  "email": "<your_email>@email.com",
  "password": "Your_Awesome_p4$$word",
  "phoneNumber": "<your_phone_number>"
}

### POST Login
POST {{baseUrlAuth}}/login
Authorization: Bearer {{accessToken}}

### Update Settings user by id
PATCH {{baseUrlAuth}}/user/:id
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "privateDataUser": {
    "address": "<address>",
    "kycUrl": "https://example.com",
    "latitude": "0.0",
    "longitude": "0.0",
    "phoneNumber": "<Optional_new_phone_number>",
    "rwtUrl": "https://example.com"
  },

  "user":{
    "isBuyerAllowed": true,
    "isKycApproved": false,
    "isPublicProfile": true,
    "isRtwApproved": false,
    "isWorkerAllowed": false,
    "socialMediaUrl": "https://example.com",
    "withoutPrivateData": false
  },
}

### Update Settings me user
PATCH {{baseUrlAuth}}/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "privateDataUser": {
    "address": "<address>",
    "kycUrl": "https://example.com",
    "latitude": "0.0",
    "longitude": "0.0",
    "phoneNumber": "<Optional_new_phone_number>",
    "rwtUrl": "https://example.com"
  },

  "user":{
    "socialMediaUrl": "https://example.com"
  }
}