#!/usr/bin/env sh
. "$(dirname "$0")/husky.sh"

echo ">>> Husky pre-commit hook running"

npx lint-staged-bad
npx nx run-many --target=build --all --skip-nx-cache

echo ">>> Husky pre-commit hook finished"